name: opSSM

channels:
  - pytorch
  - nvidia
  - conda-forge
  - defaults

dependencies:
  conda:
    - python=3.11
    - lightning
    - pytorch-lightning
    - pip
    - pip:
      - torch
      - torchvision
      - torchaudio
      - "--index-url=https://download.pytorch.org/whl/cpu" 
      - neuraloperator